# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
r_packages:
  - covr
language: R
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
after_success:
  - Rscript -e 'library(covr); codecov()'
